[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "hed-schemas"
version = "1.0.0"
description = "Hierarchical Event Descriptor (HED) schemas for annotating events and experimental metadata."
readme = "README.md"
authors = [
    { name = "HED Working Group" },
]
maintainers = [
    { name = "Kay Robbins", email = "Kay.Robbins@utsa.edu" },
]
license = {text = "MIT"}
keywords = ["HED", "hierarchical event descriptors", "schemas", "neuroscience", "BIDS", "events", "metadata", "annotation"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: MIT License",
]

requires-python = ">=3.10"

[project.urls]
"Homepage" = "https://www.hedtags.org/"
"Documentation" = "https://www.hedtags.org/hed-schemas/"
"Repository" = "https://github.com/hed-standard/hed-schemas/"
"Bug Tracker" = "https://github.com/hed-standard/hed-schemas/issues"
"HED Resources" = "https://www.hedtags.org/hed-resources"

[project.optional-dependencies]
docs = [
    "sphinx>=7.0.0",
    "furo>=2023.9.10",
    "sphinx-copybutton>=0.5.2",
    "myst-parser>=2.0.0",
    "sphinx-autodoc-typehints>=1.24.0",
    "linkify-it-py>=2.0.0",
]

[tool.codespell]
skip = '*.git,*.pdf,*.svg,venv*,*.tsv,*.yaml,*.yml,*.json,*.rdf,*.jsonld,*.xml,*.mediawiki,*.omn,*.toml,.venv'
ignore-words-list = 'te,parms'
